/*	DO NOT EDIT THIS FILE !
 *	To change database parameters, use the global configuration.
 */
module.exports = {
	use_vcap_service : "##db-use_vcap_service##",
	username : "##db-username##",
	password : "##db-password##",
	hostname : "##db-hostname##",
	port : ##db-port##,
	name : "##db-name##";
}
