/*	DO NOT EDIT THIS FILE !
 *	To change database parameters, use the global configuration.
 */
function db-info() {
	this.db-use_vcap_service="##db-use_vcap_service##";
	this.db-username="##db-username##";
	this.db-password="##db-password##";
	this.db-hostname="##db-hostname##";
	this.db-port="##db-port##";
	this.db-name="##db-name##";
}
