/*	DO NOT EDIT THIS FILE !
 *	To change server parameters, use the global configuration.
 */
function nodeServer-param() {
	this.processTitle="##nodeServer-processTitle##";
	this.port="##nodeServer-port##";
}
