/*	DO NOT EDIT THIS FILE !
 *	To change server parameters, use the global configuration.
 */
function nodeServer-param() {
	this.hostname="##nodeServer-hostname##";
	this.port="##nodeServer-port##";
}
